local SwordLadder = require(script.Parent:WaitForChild("SwordLadder"))

local GameConfig = {
    ROUND_DURATION = 480,
    INTERMISSION_DURATION = 15,
    POST_ROUND_DURATION = 10,
    MIN_PLAYERS_TO_START = 2,
    MAX_TIER = #SwordLadder - 1,
    DEATH_TIER_PENALTY = 1,
    ENABLE_DEATH_TIER_LOSS = true,
    WIN_RULE = "DarkheartFinalKill",

    SERVER_LIST_REFRESH_SECONDS = 12,
    SERVER_BROWSER_RATE_LIMIT_SECONDS = 3,
    TELEPORT_RATE_LIMIT_SECONDS = 5,

    SERVER_REGISTRY_HEARTBEAT_SECONDS = 5,
    SERVER_REGISTRY_TTL_SECONDS = 30,
    SERVER_LIST_MAX_RESULTS = 50,

    ENABLE_ANTI_EXPLOIT = true,
    ANTI_EXPLOIT_CHECK_INTERVAL = 0.2,
    ANTI_EXPLOIT_WALKSPEED_MAX = 16,
    ANTI_EXPLOIT_JUMPPOWER_MAX = 50,
    ANTI_EXPLOIT_JUMPHEIGHT_MAX = 7.5,
    ANTI_EXPLOIT_ENFORCE_EXACT_MOVEMENT_STATS = false,
    ANTI_EXPLOIT_MOVEMENT_TOLERANCE = 0.25,

    ANTI_EXPLOIT_AIRTIME_MAX_SECONDS = 7,
    ANTI_EXPLOIT_MAX_SPEED_STUDS_PER_SEC = 45,
    ANTI_EXPLOIT_MAX_STEP_STUDS = 16,
    ANTI_EXPLOIT_LINEAR_VELOCITY_MAX = 80,

    ANTI_EXPLOIT_WINDOW_SECONDS = 1.2,
    ANTI_EXPLOIT_WINDOW_SPEED_MAX = 34,
    ANTI_EXPLOIT_ZIGZAG_MIN_SPEED = 26,
    ANTI_EXPLOIT_ZIGZAG_RATIO_MAX = 2.25,

    ANTI_EXPLOIT_NEAR_PLAYER_DISTANCE = 8,
    ANTI_EXPLOIT_NEAR_PLAYER_SPEED_MAX = 30,

    ANTI_EXPLOIT_TELEPORT_GRACE_SECONDS = 1.25,
    ANTI_EXPLOIT_SPAWN_GRACE_SECONDS = 2.0,
    ANTI_EXPLOIT_STAT_SIGNAL_EXTRA_GRACE_SECONDS = 0.75,
    ANTI_EXPLOIT_CLIENT_REPORT_RATE_LIMIT_SECONDS = 0.35,

    -- Kick/scoring behavior
    ANTI_EXPLOIT_KICK_SCORE = 3.5,
    ANTI_EXPLOIT_DEFAULT_VIOLATION_SCORE = 1.0,
    ANTI_EXPLOIT_REASON_COOLDOWN_SECONDS = 0.45,
    ANTI_EXPLOIT_REASON_HIT_WINDOW_SECONDS = 6.0,
    ANTI_EXPLOIT_SUSPICION_DECAY_PER_SECOND = 0.45,
    ANTI_EXPLOIT_STAT_TAMPER_HITS_TO_KICK = 2,
    ANTI_EXPLOIT_KICK_ON_ANY_VIOLATION = false,
    ANTI_EXPLOIT_KICK_ON_STAT_CHANGE_TAMPER = false,

    -- False-positive protection
    ANTI_EXPLOIT_MIN_MOVEMENT_SAMPLES = 4,
    ANTI_EXPLOIT_CONSECUTIVE_STEP_VIOLATIONS = 2,
    ANTI_EXPLOIT_CONSECUTIVE_VELOCITY_VIOLATIONS = 2,
    ANTI_EXPLOIT_CONSECUTIVE_WINDOW_VIOLATIONS = 2,
    ANTI_EXPLOIT_CONSECUTIVE_NEAR_PLAYER_VIOLATIONS = 2,
    ANTI_EXPLOIT_CONSECUTIVE_AIRTIME_VIOLATIONS = 2,
    ANTI_EXPLOIT_CONSECUTIVE_CLIENT_REPORTS = 2,

    -- Hard violation multipliers
    ANTI_EXPLOIT_HARD_TELEPORT_MULTIPLIER = 2.2,
    ANTI_EXPLOIT_HARD_VELOCITY_MULTIPLIER = 1.8,

    -- Reach validation (server-side combat)
    ANTI_EXPLOIT_REACH_MAX_STUDS = 16,
    ANTI_EXPLOIT_REACH_BUFFER_STUDS = 2.5,
    ANTI_EXPLOIT_REACH_VERTICAL_MAX_STUDS = 18,
    ANTI_EXPLOIT_REACH_HARD_BUFFER_STUDS = 8,
    ANTI_EXPLOIT_REACH_VIOLATIONS_TO_KICK = 2,
    ANTI_EXPLOIT_REACH_VIOLATION_SCORE = 3.0,
    ANTI_EXPLOIT_REACH_REASON_COOLDOWN_SECONDS = 0.25,

    -- Lag compensation for movement checks
    ANTI_EXPLOIT_LAG_SPIKE_DT = 0.45,
    ANTI_EXPLOIT_LAG_SPIKE_STEP_BUFFER = 18,
}

return table.freeze(GameConfig)


